server:
  port: 7071
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心实例的主机名
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
